package models.utils;

public enum ErrorModel {
    EMPTY_STACK,
    NOT_EMPTY_DECK,
    ORIGIN_CARD_FACE_DOWN,
    DESTINATION_CARD_FACE_DOWN,
    NOT_ALLOWED_MOVE,
    INVALID_NUM_CARDS_TO_MOVE,
    ALREADY_FACE_UP;
}
